name: Publish Extension

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Publish to Visual Studio Marketplace
      - name: Publish to VS Code Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}

      # Publish to OpenVSX Registry
      - name: Publish to OpenVSX Registry
        run: npx ovsx publish -p ${{ secrets.OVSX_PAT }}
