name: Publish Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (e.g., 1.2.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Get current version
        id: get_version
        run: echo "current_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Suggest next version
        id: suggest_version
        run: |
          current=${{ steps.get_version.outputs.current_version }}
          IFS='.' read -r major minor patch <<< "$current"
          next_minor=$((minor + 1))
          echo "suggested_version=$major.$next_minor.0" >> $GITHUB_OUTPUT
        shell: bash

      - name: Update package.json version
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Git Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "Release v${{ inputs.version }}"
          git tag "v${{ inputs.version }}"
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish to Visual Studio Marketplace
      - name: Publish to VS Code Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}
        
      # Publish to OpenVSX Registry
      - name: Publish to OpenVSX Registry
        run: npx ovsx publish -p ${{ secrets.OVSX_PAT }} 